# Generated by Django 6.0.4 on 2026-05-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='member_type',
            field=models.CharField(choices=[('sarbaz', 'Сарбаз'), ('commander', 'Бөлімше командирі')], default='sarbaz', max_length=20, verbose_name='Тип участника'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
