# Generated by Django 6.0.4 on 2026-05-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clubmember_member_type_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Жоспарда'), ('done', 'Орындалды')], default='upcoming', max_length=20, verbose_name='Статус'),
        ),
    ]
