# Generated by Django 6.0.4 on 2026-05-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Ұпай саны'),
        ),
    ]
