# Generated by Django 6.0.4 on 2026-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clubmember_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='drill_score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Саптық дайындық (1-5)'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='first_aid_score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Алғашқы көмек (1-5)'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='navigation_score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Бағдарлау (1-5)'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='patriotism_score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Патриотизм (1-5)'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='shooting_score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Атыс дайындығы (1-5)'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='tactical_score',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Тактикалық дайындық (1-5)'),
        ),
    ]
