# Generated by Django 6.0.4 on 2026-05-02 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clubmember_drill_score_clubmember_first_aid_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-date'], 'verbose_name': 'Жетістік', 'verbose_name_plural': 'Жетістіктер'},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='points',
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='fa-trophy', help_text='Font Awesome иконкасы, мысалы: fa-medal, fa-trophy, fa-star', max_length=50, verbose_name='Иконка (fa-...)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Күні'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Сипаттама'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clubmember', verbose_name='Сарбаз'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Атауы'),
        ),
    ]
