# Generated by Django 6.0.4 on 2026-05-02 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_achievement_options_remove_achievement_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.clubmember', verbose_name='Сарбаз'),
        ),
    ]
