# Generated by Django 6.0.4 on 2026-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_achievement_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('date', models.DateTimeField(verbose_name='Күні мен уақыты')),
                ('duration', models.PositiveIntegerField(default=90, verbose_name='Ұзақтығы (минут)')),
                ('location', models.CharField(default='Спорт залы', max_length=200, verbose_name='Өтетін жері')),
                ('instructor', models.CharField(default='Ахан А.Д.', max_length=100, verbose_name='Жаттықтырушы')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Максимум қатысушы')),
                ('status', models.CharField(choices=[('planned', 'Жоспарда'), ('ongoing', 'Жүріп жатыр'), ('completed', 'Аяқталды')], default='planned', max_length=20, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainings/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Жаттығу',
                'verbose_name_plural': 'Жаттығулар',
                'ordering': ['-date'],
            },
        ),
    ]
