# Generated by Django 6.0.4 on 2026-05-02 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('content', models.TextField(verbose_name='Мәтін')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Сурет')),
                ('category', models.CharField(choices=[('general', 'Жалпы'), ('training', 'Жаттығу'), ('achievement', 'Жетістік'), ('event', 'Іс-шара')], default='general', max_length=20, verbose_name='Санат')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Жарияланған күні')),
                ('is_published', models.BooleanField(default=True, verbose_name='Жарияланған')),
            ],
            options={
                'verbose_name': 'Жаңалық',
                'verbose_name_plural': 'Жаңалықтар',
                'ordering': ['-date'],
            },
        ),
    ]
